version: '3.8'

services:
  app:
    build: .
    container_name: my_fastcgi_server
    expose:
      - "81"
  
  proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/proxy_nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
